[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
ENVIRONMENT = "production"

[[services]]
name = "bestseller-notifications"
